"""Persistent radical-Voronoi topology (spec 2.5b).

Raw face counts are brittle: tiny displacements create and destroy small
faces.  Cells are therefore classified by their face-adjacency graph after a
*persistence filter*: a face is dropped iff its gap exceeds ``g_cut`` AND its
relative area is below ``a_cut`` -- i.e. only faces that are both geometrically
marginal and generated by a distant neighbour are treated as noise.

The topology is encoded as the face-adjacency graph, not the raw face count,
and hashed with our own colour-refinement (Weisfeiler-Lehman style) canonical
hash -- VoroTop is deliberately not assumed installable (spec).  WL refinement
is not a complete graph invariant in general; for the reference cells here it
separates every class (gate T8), and any collision would merge classes, never
invent spurious distinctions.

Reference targets the classifier must reproduce on perfect lattices:
``3^8`` (K=4), ``3^2 4^7`` (K=3), ``4^10`` (K=2), ``4^11`` (K=1), the rhombic
dodecahedron ``4^12`` (FCC), the cube ``4^6`` (SC) and the hexagonal prism
``4^6 6^2`` (simple hexagonal).
"""

from __future__ import annotations

import hashlib
from dataclasses import replace

import numpy as np

from ..geometry.tangential import Cell

__all__ = ["face_adjacency", "face_filter", "p_vector", "persistence", "topo_hash"]


def face_filter(cell: Cell, g_cut: float, a_cut: float) -> Cell:
    """Drop faces with ``gap > g_cut`` AND ``area/S < a_cut``; returns a new Cell.

    ``V`` is left as the full cell volume (dropping a sliver face does not move
    volume anywhere physical); ``S`` and ``Q_iso`` are recomputed over the kept
    faces so downstream shape scores see the filtered surface.
    """
    keep = ~((cell.face_gaps > g_cut) & (cell.face_areas / cell.S < a_cut))
    if keep.all():
        return cell
    if not keep.any():
        raise ValueError("face filter removed every face; the cuts are nonsense")
    S = float(cell.face_areas[keep].sum())
    if cell.dim == 3:
        Q = 36.0 * np.pi * cell.V**2 / S**3
    else:
        Q = 4.0 * np.pi * cell.V / S**2
    return replace(
        cell,
        S=S,
        Q_iso=Q,
        n_faces=int(keep.sum()),
        face_distances=cell.face_distances[keep],
        face_areas=cell.face_areas[keep],
        face_separations=cell.face_separations[keep],
        face_sigmas=cell.face_sigmas[keep],
        face_neighbours=cell.face_neighbours[keep],
        face_vertices=tuple(l for l, k in zip(cell.face_vertices, keep) if k),
        r_in=float(cell.face_distances[keep].min()),
    )


def face_adjacency(cell: Cell) -> list[set]:
    """Adjacency of the (kept) faces: two faces are adjacent iff they share an edge
    (>= 2 vertices in 3D, >= 1 in 2D)."""
    need = 2 if cell.dim == 3 else 1
    vsets = [set(loop) for loop in cell.face_vertices]
    n = len(vsets)
    adj = [set() for _ in range(n)]
    for i in range(n):
        for j in range(i + 1, n):
            if len(vsets[i] & vsets[j]) >= need:
                adj[i].add(j)
                adj[j].add(i)
    return adj


def p_vector(cell: Cell) -> tuple:
    """Sorted polygon edge counts: the degree of each face in the face graph.

    On a closed unfiltered 3D cell this equals the sorted vertex counts of the
    face polygons (each polygon edge is shared with exactly one other face);
    after filtering it counts only edges to kept faces, which is the documented
    contraction convention.  In 2D every face is an edge with two neighbours;
    the informative quantity is the number of faces, returned as ``(n,)``.
    """
    if cell.dim == 2:
        return (cell.n_faces,)
    adj = face_adjacency(cell)
    return tuple(sorted(len(a) for a in adj))


def topo_hash(cell: Cell, *, rounds: int | None = None) -> str:
    """Canonical colour-refinement hash of the face-adjacency graph.

    Initial colour = face degree; each round rehashes (own colour, sorted
    neighbour colours); the certificate is the sorted colour multiset of every
    round.  Isomorphic face graphs always collide (the hash is an invariant);
    the reference classes of the T8 gate are pairwise separated.
    """
    adj = face_adjacency(cell)
    n = len(adj)
    if rounds is None:
        rounds = max(3, n)
    colours = [len(a) for a in adj]
    certificate = [tuple(sorted(colours))]
    for _ in range(rounds):
        new = [
            hash((colours[i], tuple(sorted(colours[j] for j in adj[i]))))
            for i in range(n)
        ]
        # canonicalise hash values to small ints so the certificate is stable
        order = {h: k for k, h in enumerate(sorted(set(new)))}
        colours = [order[h] for h in new]
        certificate.append(tuple(sorted(colours)))
        if len(set(colours)) == n:
            break
    blob = repr((cell.dim, certificate)).encode()
    return hashlib.sha256(blob).hexdigest()[:16]


def persistence(cell: Cell, g_grid, a_grid) -> float:
    """Fraction of the (g_cut, a_cut) grid on which the topology is the modal one.

    1.0 means the cell's face graph is identical across every filter setting --
    a topologically robust cell; values near ``1/len(grid)`` mean the topology
    is an artefact of the filter.
    """
    hashes = []
    for g in g_grid:
        for a in a_grid:
            try:
                hashes.append(topo_hash(face_filter(cell, g, a)))
            except ValueError:
                hashes.append("degenerate")
    vals, counts = np.unique(hashes, return_counts=True)
    return float(counts.max() / len(hashes))
